name: Build and Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libcurl4-openssl-dev
      - name: Diagnose curl headers
        run: |
          grep -R "CURL_VERSION_COOKIE" /usr/include/curl || echo "⚠️ COOKIE macro not found in distro headers!"
          grep -R "define LIBCURL_VERSION_NUM" /usr/include/curl/curlver.h
          curl --version
      - name: Install curl dev headers
        run: |
          sudo apt-get update
          sudo apt-get install --reinstall -y libcurl4-openssl-dev
          dpkg -L libcurl4-openssl-dev | grep curl/curlver.h

      - name: Build project
        run: make

      - name: Run tests
        run: make test
