name: Build and Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      GITHUB: "1"  # Used in tests to skip certain cases inside CI

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libcurl4-openssl-dev tor netcat

      - name: Start Tor
        run: |
          tor &
          echo "Waiting for Tor to bootstrap..."
          for i in {1..30}; do
            if nc -z 127.0.0.1 9050; then
              echo "Tor is running!"
              break
            fi
            sleep 1
          done

          if ! nc -z 127.0.0.1 9050; then
            echo "Tor did not start in time." >&2
            exit 1
          fi

      - name: Build project
        run: make

      - name: Run tests
        run: make test
